#!/bin/bash

LIB_PATH="scripts/_lib.lua";

PREFIX="--[[ AUTOGENERATED LIBRARY ]] "

parsedLib=$(luamin -f $LIB_PATH)

update() {
	sed -i '1s/.*/'"$PREFIX$parsedLib"'/' "$1"
}

update "scripts/universal_marker.lua"
update "scripts/clock.lua"
update "scripts/signal_iterator.lua"
update "scripts/value_iterator.lua"
update "scripts/iterator.lua"
