#!/bin/bash

LIB_PATH="lib.lua";

PREFIX="--[[ AUTOGENERATED LIBRARY ]] "

parsedLib=$(luamin -f $LIB_PATH)

update() {
	sed -i '1s/.*/'"$PREFIX$parsedLib"'/' "$1"
}

update "aai/universal_marker.lua"
update "aai/sync/clock.lua"
