--[[ AUTOGENERATED LIBRARY ]] lib={}lib.CLOCK_SIGNAL='signal-A'function lib.passSignals(...)local a={...}if#a==0 then out=red;return end;if out==nil then out={}end;for b,c in ipairs(a)do out[c]=red[c]end end;function lib.createTrigger(d)delay=math.maxinteger;irq=d end;function lib.synchronize()lib.createTrigger(lib.CLOCK_SIGNAL)end

-- desc: clock

if out[lib.CLOCK_SIGNAL] == 0 then
    out = { [lib.CLOCK_SIGNAL] = 1 }
    delay = 0
else
    out = {}
    delay = 20
end
