--[[ AUTOGENERATED LIBRARY ]] lib={}lib.CLOCK_SIGNAL='signal-A'lib.MAX_DELAY=60*60*60*24*365;function lib.passSignals(...)local a={...}if#a==0 then out=red;return end;if out==nil then out={}end;for b,c in ipairs(a)do out[c]=red[c]end end;function lib.createTrigger(d)delay=lib.MAX_DELAY;irq=d end;function lib.synchronize()lib.createTrigger(lib.CLOCK_SIGNAL)end;function lib.reset()out={}var={}end

-- desc: iterator
-- iterates endlessly, but allows to specify the amount of entries (L) instead

local INDEX_SIGNAL = 'signal-I';
local ENTRY_COUNT_SIGNAL = 'signal-L';

function getIndex()
	if (type(var.lastIndex) ~= 'number') then
		return 0;
	end

	local maxIndex = red[ENTRY_COUNT_SIGNAL];

	if (maxIndex == 0) then
		-- if no max index specified then iterate endlessly
		return var.lastIndex + 1;
	end

	return (var.lastIndex + 1) % maxIndex;
end

index = getIndex();
out[INDEX_SIGNAL] = index;
var.lastIndex = index;

lib.synchronize();
