--[[ AUTOGENERATED LIBRARY ]] lib={}lib.CLOCK_SIGNAL='signal-A'lib.MAX_DELAY=60*60*60*24*365;function lib.passSignals(...)local a={...}if#a==0 then out=red;return end;if out==nil then out={}end;for b,c in ipairs(a)do out[c]=red[c]end end;function lib.createTrigger(d)delay=lib.MAX_DELAY;irq=d end;function lib.synchronize()lib.createTrigger(lib.CLOCK_SIGNAL)end

-- desc: universal marker
-- FIXME: after last zone updated the coordinates stay and the tile cannot be marked by other zones

out = {};

local MARKER_SIGNAL_NAME = 'zone-disc-white'

local TARGET_ZONES = {
    ['iron-ore'] = 'zone-arrow-ne-cyan',
    ['copper-ore'] = 'zone-arrow-ne-orange',
    ['stone'] = 'zone-arrow-ne-yellow',
    ['coal'] = 'zone-arrow-ne-black',
    ['uranium-ore'] = 'zone-arrow-ne-green',
    ['signal-enemy-unit-spawner'] = 'zone-x-red',
    ['signal-enemy-turret'] = 'zone-x-red'
}

-- check if tile contains target object and mark it
for targetSignal, zoneSignal in pairs(TARGET_ZONES) do
    if red[targetSignal] > 0 then
        out[TARGET_ZONES[targetSignal]] = 1
        break;
    end
end

lib.passSignals('signal-x-tile', 'signal-y-tile');

lib.createTrigger(MARKER_SIGNAL_NAME);
